DROP DATABASE IF EXISTS ESPAGUA;
CREATE DATABASE IF NOT EXISTS ESPAGUA;
USE ESPAGUA;

SELECT 'Creando estructura de BBDD' as 'INFO';

DROP TABLE IF EXISTS Cuencas,
                     Embalses,
                     Capacidad,
                     Mediciones;

CREATE TABLE Cuencas (
    ID_CUENCA INT AUTO_INCREMENT PRIMARY KEY,
    CUENCA VARCHAR(50)
);

CREATE TABLE Embalses (
    ID_EMBALSE INT AUTO_INCREMENT PRIMARY KEY,
	ID_CUENCA INT,
    EMBALSE VARCHAR(50),
	ELECTRICO INT,
    FOREIGN KEY (ID_CUENCA) REFERENCES Cuencas(ID_CUENCA)
);

CREATE TABLE Capacidad (
	ID_CAPACIDAD INT AUTO_INCREMENT PRIMARY KEY,
	CAPACIDAD DECIMAL (10, 2)
);
CREATE TABLE Mediciones (
    ID_MEDICION INT AUTO_INCREMENT PRIMARY KEY,
    ID_EMBALSE INT,
    FECHA DATE,
	ID_CAPACIDAD INT,
    AGUA_ACTUAL DECIMAL(10, 2),
    FOREIGN KEY (ID_EMBALSE) REFERENCES Embalses(ID_EMBALSE),
	FOREIGN KEY (ID_CAPACIDAD) REFERENCES Capacidad(ID_CAPACIDAD)
);